Set endpoint value from env var
huggingface/hf-hub pull request #50
Opened 2024-03-22 06:53 UTC by Adamska1008

If environment variable `HF_ENDPOINT` exists, use it to build api.

2024-03-25 13:04 UTC, yosefl20 reviewed
nice

2024-03-29 11:23 UTC, kulame commented
When was this feature released, I also need this feature. HuggingFace is blocked in China

2024-03-29 11:33 UTC, Adamska1008 commented
> When was this feature released, I also need this feature. HuggingFace is blocked in China

Never know, not one of the maintainers. The crate hasn't been updated for six months.

2024-03-29 11:40 UTC, kulame commented
> > When was this feature released, I also need this feature. HuggingFace is blocked in China
> 
> Never know, not one of the maintainers. The crate hasn't been updated for six months.

Perhaps we need fork a chinese version

2024-05-02 22:50 UTC, pi314ever commented
Adding this to `tokio.rs` would be nice as well so that the changes are symmetrical.

2024-07-12 10:06 UTC, theta-lin commented
@Narsil @McPatate Dear maintainers, this feature is very important for people living in places where https://huggingface.co/ is blocked such as in China. A very easy workaround in these situations is to set `HF_ENDPOINT` to a mirror site such as https://hf-mirror.com/.

There are of course other ways to access Hugging Face when it is blocked. Unfortunately that requires the usage of proxy or VPN, which might be troublesome to set up considering that downstream projects like text-embeddings-inference are frequently run on containers and servers.

2024-07-23 11:31 UTC, McPatate requested changes
lgtm! small nit on the code

2024-09-26 19:07 UTC, dvaldivia commented
Seems like the comment has been taken care of @McPatate can you take a look?

2024-09-27 00:12 UTC, sidharthrajaram commented
+1 on this PR! Thanks @Adamska1008

2024-12-06 02:00 UTC, holmofy commented
This feature is very useful for users in mainland China

2024-12-09 12:47 UTC, McPatate approved these changes

2024-12-09 12:47 UTC, merged